{
    "name": "Customer Portal",
    "summary": "Matter Customer Portal",
    "author": "Babatope Ajepe",
    "website": "http://www.yourcompany.com",
    "category": "Customization",
    "version": "15.0.1.7.0",
    "depends": [
        "base",
        "website",
        "portal",
        "sale_crm",
        "purchase",
        "pol_on_so",
        "sale_stock",
        "purchase_stock",
        "sale_management",
        "website_enterprise",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/res_partner.xml",
        "views/crm_lead.xml",
        "views/sale_order.xml",
        "views/portal.xml",
        "views/purchase_order.xml",
    ],
    "assets": {
        "website.assets_frontend": [
            "website_customer_portal/static/src/js/accordion.js",
            "website_customer_portal/static/src/scss/desktop_styles.scss",
            "website_customer_portal/static/src/scss/tablet_styles.scss",
            "website_customer_portal/static/src/scss/mobile_styles.scss",
            "website_customer_portal/static/src/scss/style.scss",
        ],
    },
}
